name: Vitaly
options:
  bundleIdPrefix: com.perfectfools
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    INFOPLIST_FILE: iOSHealth/Resources/Info.plist

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "11.0.0"
  GoogleGenerativeAI:
    url: https://github.com/google/generative-ai-swift
    from: "0.5.0"

targets:
  Vitaly:
    type: application
    platform: iOS
    sources:
      - path: iOSHealth
        excludes:
          - "**/*.md"
          - "**/*.example"
          - "**/iOSHealthApp.swift"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.perfectfools.vitaly
        PRODUCT_NAME: Vitaly
        CODE_SIGN_ENTITLEMENTS: iOSHealth/iOSHealth.entitlements
        TARGETED_DEVICE_FAMILY: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: GoogleGenerativeAI
        product: GoogleGenerativeAI
    entitlements:
      path: iOSHealth/iOSHealth.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.background-delivery: true
        com.apple.developer.applesignin:
          - Default

  VitalyTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: iOSHealthTests
    dependencies:
      - target: Vitaly
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.perfectfools.vitaly.tests

  VitalyUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: iOSHealthUITests
    dependencies:
      - target: Vitaly
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.perfectfools.vitaly.uitests

schemes:
  Vitaly:
    build:
      targets:
        Vitaly: all
        VitalyTests: [test]
        VitalyUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - VitalyTests
        - VitalyUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
